<div class="row blocks">
	<div class="col-md-12 col-lg-12 col-xl-12 col-sm-12 col-12">
		<div style="background: #eee;border: 2px solid #ddd;border-radius: 5px;padding: 2%;margin-bottom:3%;">
			<?php if($this->uri->segment(1)=='privacy-policy'): ?>
			<h4 class="text-center">PRIVACY POLICY</h4>
			<p>Thanks for visiting “Express Deal”, a section of newindianexpress.com, the website of Express Network Private Limited (ENPL).</p>
			<p>Your privacy is our priority and we are committed towards protecting it. We do not publish, sell or rent any personal information to any third party without your consent.</p>
			<p>We may change our privacy policy whenever necessary, without any notice.</p>
			<p>The privacy policies listed below are applicable to our services that fall under the website newindianexpress.com and Express Deal Section .The moment you visit our site, you will be bound by this Privacy Policy, terms of use and terms and conditions hosted on this site. If you do not wish to agree, you may not access our site.</p>
			<p>When you accept the Privacy Policy, and the Terms and Conditionsand Terms of use while registering, you are consenting to use and disclose your personal information in accordance with this Privacy Policy. The moment you accept it during registration or while transacting with us, this privacy policy gets effective.</p>
			<p>While registering with us or availing any service from us, via website, telephone search, SMS and WAP or any other Media medium where we offer services, you may be asked to provide information such as Name, Residence Address, Email Address, Phone Number and similar personal information.</p>
			<p>We use third-party service providers to processpurchasesmade by you through their links to help us understand our users’ interests better. Along with this, our site contains links to third-party sites with their own privacy policies. The moment you click on it and leave our website, we would not be responsible for the security of your informationthat is submitted to or collected by them  as they would be out of our control.</p>
			<p>We use reputable third party/s links to serve the advertisements that you see on our pages.  In the course of serving advertisements, our third-party advertiser may place or recognize a unique “cookie” on your browser and may use information (not including your name, address, e-mail address) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.</p>
			<p>You acknowledge that you are disclosing Personal Information voluntarily. Once the registration process is complete or once any of our services is availed, if you wish not to disclose any of your personal information, you may refrain from disclosing. However, without your personal information, your registration may remain incomplete and/or you would not be able to avail our services.</p>
			<h4>Children's Privacy</h4>
			<p>Our website content is for the general audience and is not intended for children under 18.</p>
			<p>Your Privacy is our utmost priority We value your privacy and we are always putting all our efforts into protecting your privacy. We are grateful for your trust.</p>
			<p>Privacy Guarantee</p>
			<p>Personal Information may be shared only under one or more of the following circumstances:</p>
			<p>(a) If we have your consent or deemed consent to do so.</p>
			<p>(b) If we are compelled by law (including court orders) to do so.</p>
			<p>ENPL gives you the ability to edit your account information and preferences at any time.</p>
			<p>While we strive to use a commercially acceptable means to protect the personal information you provide, we cannot guarantee its security. Therefore, you acknowledge and agree that we assume no liability regarding the theft, loss, alteration or misuse of personal or other information or Content, including, without limitation, such information that has been provided to third parties or other users, or with regards to the failure of a third party to abide by the agreement between us and such third party.</p>
			<p>If you have any comment or question with regard to our privacy policy, you may contact us at the following e-mail address.</p>
			<p>writetous@newindianexpress.com</p>
			
			<?php endif; ?>
			<?php if($this->uri->segment(1)=='terms-of-use'): ?>
			<h4 class="text-center">TERMS OF USE</h4>
			<p>Welcome to Express Deal, a section of newindianexpress.com, the website of Express Network Private Limited (ENPL).</p>
			<p>The following are the rules ("Terms") that govern use of the Website www.newindianexpress.com. By using, adding information, or visiting the Site, you expressly agree to be bound by these Terms and to follow these Terms and all applicable laws and regulations governing the Site. Express Network Private Limited reserves the right to change these Terms at any time, effective immediately upon posting on the Site.</p>
			<p>Permitted Use</p>
			<p>You agree that you are only authorized to visit, view, and retain a copy of pages of this Site for your own personal use, and that you shall not duplicate, download, publish, modify, scrape, or otherwise distribute the material on this Site for any commercial use, or for any purpose other than as described in these Terms.</p>
			<p>Registering with Express Deal</p>
			<p>In order to take advantage of the features on the Site, you will be required to register with the Express Deal and the use of any personal information that you provide during any registration process is governed by the site’sprivacy policyhosted on this site.</p>
			<p>Links and Search Results</p>
			<p>The Site may automatically produce search results that reference or link to offers across the world wide web. ENPL or the website has no control over these sites or the content within them. ENPL cannot guarantee, represent, or warrant that the content contained in these sites is accurate, legal, and/or inoffensive. ENPL does not endorse the content of any third-party site, nor do we warrant that it will not contain viruses or otherwise impact your computer. By using the Site to search for or link to another site, you agree and understand that you may not make any claim against ENPL or the website for any damages or losses, whatsoever, resulting from your use of the Site to obtain search results or to link to another site. newindianexpress.com is a news website that consists of the blog/section of Express Deals as its affiliate channel. We show you the prices of tech products on different online stores. We do not know about the reliability and genuineness of each site and the products they are selling. All customers are advised to satisfy themselves of the same before purchasing. ENPL shall not be held responsible for any complaints/defects and the same has to be raised by you with the respective seller/online stores for proper action.   If you have a problem with a link from the Site, please notify us at writetous@newindianexpress.com, and we will investigate your claim and take any actions we deem appropriate at our sole discretion.</p>
			<p>Access and Interference</p>
			<p>You agree that you will not use any robot, spider, other automatic device, or manual process to monitor or copy our Web pages or the content contained thereon or for any other unauthorized purpose without our prior expressed written permission. You agree that you will not use any device, software, or routine to interfere or attempt to interfere with the proper working of the Site. You agree that you will not copy, reproduce, alter, modify, create derivative works from, or publicly display any content (except for your own personal, non-commercial use) from our Web site without the prior expressed written permission from us. </p>
			<p>Unauthorized Use of the Site</p>
			<p>Illegal and/or unauthorized uses of the Site, including, but not limited to, unauthorized framing of or linking to the Site or unauthorized use of any robot, spider, or other automated device on the Site, will be investigated and subject to appropriate legal action, including, without limitation, civil, criminal, and injunctive redress.</p>
			<p>Violation of the Terms</p>
			<p>You agree that monetary damages may not provide a sufficient remedy to ENPL for violations of these terms of use and you consent to injunctive or other equitable relief for such violations.</p>
			<p>DISCLAIMERS</p>
			<p>ENPL DOES NOT PROMISE THAT THE SITE WILL BE INOFFENSIVE, ERROR-FREE OR UNINTERRUPTED, OR THAT IT WILL PROVIDE SPECIFIC RESULTS FROM USE OF THE SITE OR ANY CONTENT, SEARCH, OR LINK ON IT. THE SITE AND ITS CONTENT ARE DELIVERED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. ENPL CANNOT ENSURE THAT FILES YOU DOWNLOAD FROM THE SITE WILL BE FREE OF VIRUSES OR CONTAMINATION OR DESTRUCTIVE FEATURES. ENPL DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. ENPL WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, AND PUNITIVE AND CONSEQUENTIAL DAMAGES.</p>
			<p>ENPL disclaims any and all liability for the acts, omissions, and conduct of any third-party users, , advertisers, and/or sponsors on the Site, in connection with the Site, or otherwise related to your use of the Site. ENPL is not responsible for the products, services, actions, or failure to act of any third party in connection with or referenced on the Site. Without limiting the foregoing, you may report the misconduct of users and/or third-party advertisers or service and/or product providers referenced on or included in the Site to us at writetous@newindianexpress.com.We may investigate the claim and take appropriate action, at our sole discretion.</p>
			<p>LIMITATION ON LIABILITY</p>
			<p>EXCEPT IN JURISDICTIONS WHERE SUCH PROVISIONS ARE RESTRICTED, IN NO EVENT WILL ENPL BE LIABLE TO YOU FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, EVEN IF ENPL HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
			<p>Indemnity</p>
			<p>You agree to indemnify and hold, ENPL its subsidiaries, affiliates, officers, agents, and other partners and employees harmless from any loss, liability, claim, or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your use of the Site, including your use of the Site to provide a link to another site or to upload content or other information to the Site.</p>
			<h5><u>JURISDICTION :-</u></h5>
			<p>Any dispute or difference arising out of the use of our website newindianexpress.com shall be subject to the jurisdiction of the Courts at Chennai, Tamil Nadu, India.</p>
			<?php endif; ?>
			<?php if($this->uri->segment(1)=='terms-and-condition-of-service'): ?>
			<h4 class="text-center">TERMS AND CONDITIONS OF SERVICE</h4>
			<h5>OVERVIEW</h5>
			<p>This Express Deal is operated by Express Network Private Limited (ENPL). Throughout the site, the terms “we”, “us” and “our” refer to ENPL. ENPL offers this site, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>
			<p>By visiting our site and/ or, through the link posted on the site, you agree to be bound by the following terms and conditions (“Terms of Service”, “Terms”), including those additional terms and conditions and policies referenced herein. These Terms of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content.</p>
			<p>Please read these Terms of Service carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service.</p>
			<p>Any new features or tools which are added to the current site shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.</p>
			<h5>ONLINE STORE TERMS</h5>
			<p>We provide the service as participants of affiliate advertising programmes designed to provide a means to earn advertising fee by advertising and bring the various websites like Amazon, Flipkart etc</p>
			<p>You may not use our service for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</p>
			<p>You must not transmit any worms or viruses or any code of a destructive nature.</p>
			<p>A breach or violation of any of the Terms will result in an immediate termination of your access.</p>
			<h5>GENERAL CONDITIONS</h5>
			<p>We reserve the right to refuse service to anyone for any reason at any time.</p>
			<p>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</p>
			<p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us.</p>
			<p>The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
			<h5>ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION</h5>
			<p>We are not responsible if information made available on this site/section is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site/section  is at your own risk.</p>
			<p>This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site.</p>
			<h5>MODIFICATIONS TO THE SERVICE AND PRICES</h5>
			<p>The policies and pricing of the products are as provided in the third party sites.</p>
			<p>We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.</p>
			<p>We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.</p>
			<h5>THIRD PARTY CONTENT</h5>
			<p>You may see and read advertorials, advertising, promotional or sponsored content, or links to third party websites, submitted by third parties on the Sites (“Third Party Promotional Content”). Individual advertisers and parties releasing advertisements are solely responsible for such Third Party Promotional content which may appear on the Sites or accessible at or through the Sites. The third party alone is responsible to ensure that it complies with relevant legislation, rules and regulations and that the Promotional contents are not illegal, immoral or contrary to public policy. We accept no responsibility for the content of advertising or third Party Promotional Content or third Party websites, including, without limitation, any errors, omissions or inaccuracies therein.</p>
			<p>We do not control, endorse, sponsor, recommend or otherwise accept any responsibility for such Third Party Promotional Content. The User must make all necessary inquiries before entering into any transaction or remitting monies, data, personal information, etc. or contracting with or accepting or acting on third party promotional content in any manner.</p>
			<h5>THIRD-PARTY LINKS</h5>
			<p>All contents, products and services available via our Service include materials from third-partiesover whom ENPL has no control or connection as these sites are external to us and you agree and understand that by visiting such sites you are beyond our sites and you are bound by their terms of service.</p>
			<p>Third-party links on this site may direct you to third-party websites that may or may not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and/or quality of the product displayed at third party site and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.</p>
			<p>We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions madeby your visit and/or transaction/s on those sites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</p>
			<h5>USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS</h5>
			<p>If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.</p>
			<p>We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.</p>
			<p>You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.</p>
			<h5>PERSONAL INFORMATION</h5>
			<p>Your submission of personal information through this site is governed by our Privacy Policy.</p>
			<h5>ERRORS, INACCURACIES AND OMISSIONS</h5>
			<p>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions and offers. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information if any information in the Service or on any related website is inaccurate at any time without prior notice.  No representations, warranties or guarantees whatsoever are made as to the accuracy, adequacy, reliability, completeness, suitability or applicability of the information provide in the site to a particular situation.</p>
			<p>We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.</p>
			<h5>PROHIBITED USES</h5>
			<p>In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
			<h5>DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</h5>
			<p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.</p>
			<p>We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</p>
			<p>You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.</p>
			<p>You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
			<p>In no case shall, ENPL our directors, officers, employees, contractors, interns, be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of or your inability to use any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
			<h5>INDEMNIFICATION</h5>
			<p>You agree to indemnify, defend and hold harmless ENPL and, its subsidiaries, officers, directors, contractors, interns and employees, harmless from any claim or demand, loss, cost, expenses or damages including reasonable attorneys’ fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.This clause will survive the expiry or termination of this agreement.</p>
			<h5>SEVERABILITY</h5>
			<p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
			<h5>TERMINATION</h5>
			<p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.</p>
			<p>These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.</p>
			<p>If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p>
			<h5>ENTIRE AGREEMENT</h5>
			<p>The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.</p>
			<p>These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service).</p>
			<p>Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>
			<h5>CHANGES TO TERMS OF SERVICE</h5>
			<p>You can review the most current version of the Terms of Service at any time at this page.</p>
			<p>We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p>
			<h5>PUBLICATION</h5>
			<p>This site is deemed to have published from/at Chennai, India, irrespective of the place from where the sites is accessed.</p>
			<h5>GOVERNING LAW & JURISDICTION</h5>
			<p>This Agreement shall be governed by the Indian Law.  The Courts at Chennai shall have exclusive jurisdiction over any disputes arising out of or in relation to this Agreement.</p>
			<h5>CONTACT INFORMATION</h5>
			<p>Questions about the Terms of Service should be sent to us at writetous@newindianexpress.com.</p>
			<?php endif; ?>
			<?php if($this->uri->segment(1)=='contact-us'): ?>
			<h4 class="text-center">CONTACT US</h4>
			<?php endif; ?>
		</div>
	</div>
</div>